name: pymc_vi_course

channels:
  - conda-forge
dependencies:
  - python
  - altair
  - ipython
  - ipywidgets
  - jupyter_bokeh
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - numba
  - nutpie
  - pandas
  - patsy
  - pip
  - plotly
  - polars
  - preliz
  - pyarrow
  - pymc
  - pymc-extras
  - pydot
  - python-graphviz
  - scipy
  - seaborn
  - setuptools
  - watermark
  - xlrd
  - pip:
    - kaleido
